tasks/final/src/main/java/by/baranov/drugdistribution/entity/DrugOrderStatus.java
package by.baranov.drugdistribution.entity;

public enum DrugOrderStatus {
	
	CREATED, INVOICE_CREATED, DELIVERY_IN_PROGRESS, DELIVERED;
	
	public String getName() {
		return toString();
	}
}

tasks/final/src/main/webapp/jsp/errorPage.jsp
<%@ page isErrorPage="true" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html lang="ru">
<head>
<meta charset="UTF-8">
<title>Error page</title>
</head>
<body>
	<p>
		Unfortunately there are next problem in the application: 
		
		<c:out value="${pageContext.exception.message}"/>
		
	</p>
	<a href="${pageContext.request.contextPath}/jsp/userLoginPage.jsp">Home page</a>
</body>
</html>

tasks/final/src/main/webapp/jsp/mainPage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ page import="by.baranov.drugdistribution.AppConstants"%>
<%@ page import="by.baranov.drugdistribution.command.CommandName"%>
<%@ taglib prefix="tag" tagdir="/WEB-INF/tags"%>

<html lang="ru">
<head>
	<title>Choose category</title>
	<tag:meta/>
</head>

<style>
div.container {
	text-align: center;
}
</style>

<body>
	<div class="container">
		<ul class="nav nav-pills justify-content-end" role="tablist">
			<li class="nav-item"><tag:logout /></li>
		</ul>
	</div>
	<div class="jumbotron text-center" style="margin-bottom: 0">
		<h1> 
             ${registeredUser.name} ${registeredUser.surname}, <fmt:message key="main.page.tab.title" />
		</h1>
	</div>

	<div class="container" style="margin-top: 30px">
		<br />
		<tag:check commandName="${CommandName.VIEW_ALL_USERS}">
			<a href="${pageContext.request.contextPath}/jsp/user/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_ALL_USERS}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.users"/>
			</a>
		</tag:check>
		
		<tag:check commandName="${CommandName.VIEW_ALL_PHARMACIES}">
			<a href="${pageContext.request.contextPath}/jsp/pharmacy/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_ALL_PHARMACIES}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.pharmacies"/>
			</a>
		</tag:check>
		
		<tag:check commandName="${CommandName.VIEW_ALL_DRUGS}">
			<a href="${pageContext.request.contextPath}/jsp/drug/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_ALL_DRUGS}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.drugs"/> 
            </a>
		</tag:check>

		<tag:check commandName="${CommandName.VIEW_ALL_DRUG_ORDERS}">
			<a href="${pageContext.request.contextPath}/jsp/drugOrder/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_ALL_DRUG_ORDERS}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.drug.orders"/>
			</a>
		</tag:check>
		<tag:check commandName="${CommandName.VIEW_DRUG_PROVIDER_FORM}">
			<a href="${pageContext.request.contextPath}/jsp/drugProvider/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_DRUG_PROVIDER_FORM}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.drug.providers"/>
			</a>
		</tag:check>
		<tag:check commandName="${CommandName.VIEW_ALL_DRIVER_INVOICES}">
			<a href="${pageContext.request.contextPath}/jsp/jsp/driverInvoice/
                ?${AppConstants.PARAMETER_COMMAND_NAME}=${CommandName.VIEW_ALL_DRIVER_INVOICES}" class="btn btn-info" role="button"> 
                    <fmt:message key="main.page.tab.driver.invoices"/>
			</a>
		</tag:check>
	</div>
</body>
</html>

tasks/final/src/main/webapp/jsp/userLoginPage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tag" tagdir="/WEB-INF/tags" %>
<%@ page import="by.baranov.drugdistribution.AppConstants" %>
<%@ page import="by.baranov.drugdistribution.command.CommandName" %>

<html lang="ru">

<head>
	<title>Login User</title>
	<tag:meta/>
</head>
<body>
	<c:choose>
		<c:when test="${not empty requestScope.get('lang')}">
			<fmt:setLocale value="${requestScope.get('lang')}"/>
		</c:when>
		<c:otherwise>
			<fmt:setLocale value="${cookie['lang'].value}"/>
		</c:otherwise>
	</c:choose>

	<fmt:setBundle basename="/i18n/ApplicationMessages" scope="application"/>

	<div class="container">
		<ul class="nav nav-pills justify-content-end" role="tablist">
			<li class="nav-item">
			    <a class="nav-link" href="${pageContext.request.contextPath}?lang=en"> 
				    <fmt:message key="choose.language.english"/>
			    </a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="${pageContext.request.contextPath}?lang=ru"> 
			        <fmt:message key="choose.language.russian"/>
			    </a>
			</li>
		</ul>
	</div>
	<div class="jumbotron text-center" style="margin-bottom: 0">
		<h1>
			<fmt:message key="user.login.greeting"/>
		</h1>
	</div>

	<div class="container">
		<form action="userLogin" method="POST" accept-charset="utf-8">
			<div class="form-group">
				<label for="${AppConstants.PARAMETER_USER_LOGIN}"><fmt:message key="user.login.legend"/></label> 
				<input id="${AppConstants.PARAMETER_USER_LOGIN}" type="text" class="form-control"
					placeholder="<fmt:message key="user.login.legend.input"/>" name="${AppConstants.PARAMETER_USER_LOGIN}"/>
			</div>
			<div class="form-group">
				<label for="${AppConstants.PARAMETER_USER_PASSWORD}"><fmt:message key="user.password.legend"/></label> 
				<input id="${AppConstants.PARAMETER_USER_PASSWORD}" type="password" class="form-control"
					placeholder="<fmt:message key="user.password.legend.input"/>" name="${AppConstants.PARAMETER_USER_PASSWORD}"/>
			</div>
			<input type="hidden" name="${AppConstants.PARAMETER_COMMAND_NAME}" value="${CommandName.USER_LOGIN}">
			<button type="submit" class="btn btn-info"> <fmt:message key="user.login.button"/></button>
		</form>
		<tag:error errorMessage="${errorMessage}"/>
	</div>
</body>
</html>